### ISSUE TITLE
Passing sitekey through environment variable does not work

### ISSUE THREAD

**Issue by chriscoindeskindices** [snelsi/next-recaptcha-v3#119]
**Describe the bug**
I have my sitekey in .env.local
When I set the sitekey in <ReCaptchaProvider> (in my _app.js file) using the environment variable, accessed through process.env.SITE_KEY, the value is not passed to the script.  I get a "client ID is null" error when trying to use reCaptcha.  I confirmed there is a value for that environment variable by printing it to the console.

As soon as I hardcode that sitekey into my _app.js file, reCaptcha works fine.

**To Reproduce**
1. Set the sitekey in an environment variable
2. Set the sitekey of <ReCaptchaProvider> in your _app.js or _app.tsx through the env variable using process.env

Sample code:

`function MyApp({ Component, pageProps }) {`

`  const siteKey = process.env.RECAPTCHA_SITE_KEY`
`  console.log("My siteKey: ", siteKey)`
`  return (`
`    <ReCaptchaProvider reCaptchaKey={siteKey}>`
`...`

**Expected behavior**
Recaptcha's sitekey to be set correctly

**Screenshots**

**Desktop (please complete the following information):**
- MacOS 12.6
- Chrome

**Additional context**

**Comment by snelsi** [comment]
## From the official [NextJs documentation](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser):

By default environment variables are only available in the Node.js environment, meaning they won't be exposed to the browser.

In order to expose a variable to the browser you have to prefix the variable with `NEXT_PUBLIC_`. For example:

```
NEXT_PUBLIC_ANALYTICS_ID=abcdefghijk
```

This loads `process.env.NEXT_PUBLIC_ANALYTICS_ID` into the Node.js environment automatically, allowing you to use it anywhere in your code. The value will be inlined into JavaScript sent to the browser because of the `NEXT_PUBLIC_` prefix. This inlining occurs at build time, so your various `NEXT_PUBLIC_` envs need to be set when the project is built.

**Comment by snelsi** [comment]
To fix this you should be able to just rename your `RECAPTCHA_SITE_KEY` variable to `NEXT_PUBLIC_RECAPTCHA_SITE_KEY`, and remove the passing of `reCaptchaKey={siteKey}` param to the `ReCaptchaProvider`

**Comment by chriscoindeskindices** [comment]
Thank you! That worked perfectly. Might be good to make that note in the
documentation for others as well.

*Christopher Lam*

*Vice President of Engineering, CoinDesk Indices*

*Mobile*: (310) 883-5625

*Email*: ***@***.***



250 Park Avenue South, 2nd Floor

New York, New York 10003


Learn more about *CoinDesk Indices* <https://www.coindesk.com/indices/> and
*subscribe* <https://www.coindesk.com/newsletters/> to CoinDesk newsletters.

**Comment by snelsi** [comment]
Glad I could help)

> Might be good to make that note in the documentation for others as well

It's already there, actually.

[Here:](https://github.com/snelsi/next-recaptcha-v3#generate-recaptcha-key)
![image](https://user-images.githubusercontent.com/15171036/215838479-a73e83d9-4452-43bb-a631-b3c12f91cda6.png)

[And here:](https://github.com/snelsi/next-recaptcha-v3#recaptchaprovider-props)
![image](https://user-images.githubusercontent.com/15171036/215838535-4dc7a3f3-c181-4865-9219-6f542a10a9de.png)

**Comment by snelsi** [comment]
@petrleocompel
It's quite trivial to use any `siteKey` you need. Here's some examples:

1) Redefine some private env variable as public env variable in `next.config.js`:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.GOOGLE_CAPTCHA_SITE_KEY,
  },
};
```

2) Use [build params](https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script) or [phase variable](https://github.com/vercel/next.js/blob/5e6b008b561caf2710ab7be63320a3d549474a5b/packages/next/shared/lib/constants.ts#L19-L23) to handle `siteKey` in `next.config.js`:
```ts
const { PHASE_DEVELOPMENT_SERVER, PHASE_TEST } = require("next/constants");

const getSiteKey = (phase) => {
  switch (phase) {
    case PHASE_DEVELOPMENT_SERVER:
      return "dev_site_key";
    case PHASE_TEST:
      return "test_site_key";
    default:
      return "production_site_key";
  }
};

/** @type {import('next').NextConfig} */
module.exports = (phase) => {
  const siteKey = getSiteKey(phase);
  return {
    env: {
      NEXT_PUBLIC_RECAPTCHA_SITE_KEY: siteKey,
    },
  };
};
```

3) Define separate variable for prod and test environments, pass them to the `ReCaptchaProvider` as `reCaptchaKey={siteKey}`:

next.config.js:
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_PROD_RECAPTCHA_SITE_KEY: "prod_site_key",
    NEXT_PUBLIC_TEST_RECAPTCHA_SITE_KEY: "test_site_key",
    NEXT_PUBLIC_DEV_RECAPTCHA_SITE_KEY: "dev_site_key",
  },
};
```

/recaptcha.tsx
```tsx
const Layout = ({ children }) => (
  <ReCaptchaProvider
    reCaptchaKey={
      process.env.NODE_ENV === "production"
        ? proces.env.NEXT_PUBLIC_PROD_RECAPTCHA_SITE_KEY
        : proces.env.NEXT_PUBLIC_DEV_RECAPTCHA_SITE_KEY
    }
  >
    {children}
  </ReCaptchaProvider>
);
```

/recaptcha.test.tsx
```tsx
const Layout = ({ children }) => (
  <ReCaptchaProvider
    reCaptchaKey={proces.env.NEXT_PUBLIC_TEST_RECAPTCHA_SITE_KEY}
  >
    {children}
  </ReCaptchaProvider>
);
```

4) Just pas different `siteKey` as a param to the `useReCaptcha` hook or `ReCaptcha` component:

```tsx
const TestForm = () => {
  const { executeRecaptcha } = useReCaptcha("my_test_site_key");
  return <ReCaptcha reCaptchaKey="my_other_site_key" />;
};
```

**Comment by petrleocompel** [comment]
@snelsi Yes I know about this workaround. But I was trying to solve providing ENV variable on deployment. *Not in build*. (Imagine multiple environments... This file would grow depending on number of clients). 
I know that i will have to provide it to `ReCaptchaProvider` but I asked if there is some smart way to do it via env.

**Comment by petrleocompel** [comment]
Not best solution but `getServerSideProps` solves the problem. Providing the env variable to page and using it in `ReCaptchaProvider` works.
