### ISSUE TITLE
ReCaptcha component now showing.

### ISSUE THREAD

**Issue by chriscoindeskindices** [snelsi/next-recaptcha-v3#120]
**Describe the bug**
I was able to get a token using the useReCaptcha hook.  I tried to use the ReCaptcha component according to the docs but nothing appeared in my browser and no errors were shown.

**To Reproduce**
Follow the steps in the tutorial to use the ReCaptcha component

**Expected behavior**
I expect some component to appear on the webpage.

**Desktop (please complete the following information):**

- OS: MacOS 12.6
- Chrome

**Comment by snelsi** [comment]
# From [Google Docs](https://developers.google.com/recaptcha/docs/versions):

## reCAPTCHA v3

reCAPTCHA v3 allows you to verify if an interaction is legitimate without any user interaction. It is a pure JavaScript API returning a score, giving you the ability to take action in the context of your site: for instance requiring additional factors of authentication, sending a post to moderation, or throttling bots that may be scraping content.

## reCAPTCHA v2 ("I'm not a robot" Checkbox)

The "I'm not a robot" Checkbox requires the user to click a checkbox indicating the user is not a robot. This will either pass the user immediately (with No CAPTCHA) or challenge them to validate whether or not they are human. This is the simplest option to integrate with and only requires two lines of HTML to render the checkbox.

**Comment by snelsi** [comment]
This library uses ReCaptcha V3.

V3 is designed to be invisible and do not require any interaction from the user. All checks are run in the background.

If you want to show the "I'm not a robot" button on your page, you should use V2 instead.
