### ISSUE TITLE
Add support for the Next 13 `app` directory

### ISSUE THREAD

**Issue by wxh06** [snelsi/next-recaptcha-v3#133]
### Current behavior

```
Server Error

TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

### Reproduction

<https://beta.nextjs.org/docs/upgrade-guide#step-2-creating-a-root-layout>

```tsx
// app/layout.tsx

import { ReCaptchaProvider } from "next-recaptcha-v3";

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <ReCaptchaProvider>{children}</ReCaptchaProvider>
      </body>
    </html>
  );
}
```

### Solution

See <https://beta.nextjs.org/docs/rendering/server-and-client-components#convention>

Add `"use client";` directive to the top of `src/index.tsx` or every file that imports `useState`, `useRef` or `useEffect` (`src/ReCaptcha.tsx`, `src/ReCaptchaProvider.tsx` and `src/useReCaptcha.tsx`):
<https://github.com/snelsi/next-recaptcha-v3/blob/833bb66ff8ee99449571cb1fd67b096476774603/src/index.ts#L1-L5>

**HOWEVER, Rollup ignores and does not emit `"use client";` directives in bundled script. 😅**

### Workaround

Create a separate file that begins with `"use client";` directive and re-export `ReCaptchaProvider`

#### `app/ReCaptchaProvider.tsx`

```ts
"use client";

// https://www.typescriptlang.org/docs/handbook/modules.html#re-exports
// eslint-disable-next-line import/prefer-default-export
export { ReCaptchaProvider } from "next-recaptcha-v3";
```

#### `app/layout.tsx`

```ts
import { ReCaptchaProvider } from "./ReCaptchaProvider.tsx";

// ...
```

**Comment by snelsi** [comment]
Should be fixed in v1.1.4 🦄
