### ISSUE TITLE
Add support for Checkbox

### ISSUE THREAD

**Issue by anhcao142** [snelsi/next-recaptcha-v3#151]
Hi, I can't find a way to render the Checkbox challenge. When I try using `executeRecaptcha` method it says I need to add `ReCaptcha`. But when I switch to ReCaptcha it shows nothing.

**Comment by snelsi** [comment]
If you are talking about "I'm not a robot" checkbox, then it's not possible to render using this library.`next-recaptcha-v3` uses ReCaptcha v3, which is completely invisible to the user. To render the checkbox, you need to use ReCaptcha v2. 

There are a lot of useful links and resources in the [README](https://github.com/snelsi/next-recaptcha-v3#readme). You can use that as a reference to better understand the difference.
