### ISSUE TITLE
reCaptcha script is loaded twice

### ISSUE THREAD

**Issue by ilyagru** [snelsi/next-recaptcha-v3#152]
**Describe the bug**

When the provider is connected and the page is loaded, the Google Recaptcha script is being loaded twice. That slows down the website performace and is visible in metrics reports. The issue occurs in both Development and Production.

**To Reproduce**

1. Integrate Recaptcha as per the docs (wrapping the app into the provider).
    ```tsx
    'use client'
    
    import { ReactNode } from 'react'
    import { ThemeProvider } from 'next-themes'
    import { ReCaptchaProvider } from 'next-recaptcha-v3'
    
    type Props = {
      children: ReactNode
    }
    
    export default function Providers({ children }: Props) {
      return (
        <ThemeProvider enableSystem attribute="class">
          <ReCaptchaProvider
            id="google-recaptcha-load"
            strategy="afterInteractive"
            reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
          >
            {children}
          </ReCaptchaProvider>
        </ThemeProvider>
      )
    }
    
    ```
3. Run "npm dev".
4. See the Network requests.

**Expected behavior**

The script is loaded once.

**Screenshots**

<img width="972" alt="Screenshot 2023-10-06 at 09 55 22" src="https://github.com/snelsi/next-recaptcha-v3/assets/18074511/6ddae89f-8a7e-4b2d-a9a9-94bf4b61d625">
<img width="1404" alt="Screenshot 2023-10-06 at 09 52 31" src="https://github.com/snelsi/next-recaptcha-v3/assets/18074511/7af165d9-1581-4365-80ff-0d35d533f4eb">
<img width="1013" alt="Screenshot 2023-10-06 at 09 59 08" src="https://github.com/snelsi/next-recaptcha-v3/assets/18074511/43d2c536-1e23-44b1-8a22-7f93ad6aef3b">

**Desktop (please complete the following information):**

- OS: macOS 13.5.2
- Browser: Firefox 118.0.1, Safari 16.6
- Version: v1.2.0

**Additional context**

**Comment by snelsi** [comment]
It's just something that reCaptcha does internaly for some reason 🤷‍♀️

https://github.com/google/recaptcha/issues/236
https://github.com/google/recaptcha/issues/415
https://github.com/google/recaptcha/issues/331

It adds `recaptcha__en.js` script 2 times. Once in the head, and once inside of the `grecaptcha-badge` iframe's body.
Nothing we can do on our side, sadly.
