### ISSUE TITLE
reCAPTCHA logo appears on every page across app

### ISSUE THREAD

**Issue by thathurtabit** [snelsi/next-recaptcha-v3#155]
**Describe the bug**
If using Next's route with `Link` as most people will - after `reCAPTCHA` script has been added to the page, the logo will continue to stay in the bottom right of the site on every page until a full page refresh is made.

**To Reproduce**

* Add reCaptcha
* Navigate to different pages and see the logo always follow you

**Expected behavior**
reCaptcha logo only appears on the page where reCaptcha is used - _not_ across the whole site.

**Comment by snelsi** [comment]
https://github.com/snelsi/next-recaptcha-v3/issues/136#issuecomment-1449871191

> When ReCaptchaProvider is rendered, it adds [ReCaptcha script](https://www.google.com/recaptcha/api.js) to your page. When this script is executed, it adds a global recaptcha variable, loads some internal scripts, and adds some handlers and other stuff to the HTML. Even if you remove the ReCaptchaProvider, it won't remove the stuff that ReCaptcha has loaded to the global scope.
> 
> Most of the time it's not a problem, since you actually want to load ReCaptha early, to get more user-data, and as a result, more accurate bot-detection.
> 
> If you don't like the ReCaptcha tag floating in the corner, just hide it, using the following CSS:
> ```css
> .grecaptcha-badge {
>     visibility: hidden;
> }
> ```

**Comment by ldelia** [comment]
Is there a way of adding that CSS rule on every page except for one specific one?

**Comment by snelsi** [comment]
@ldelia 
You have full control over it.

Just turn the `visibility` back in on the page you want

```css
.grecaptcha-badge {
    visibility: visible;
}
```

**Comment by ldelia** [comment]
> @ldelia You have full control over it.
> 
> Just turn the `visibility` back in on the page you want
> 
> ```css
> .grecaptcha-badge {
>     visibility: visible;
> }
> ```

Thanks, if anyone is looking for the same:

In the default layout, we can have something like this:

```
export default function RootLayout(...) {
  return (
    <...>
      <body>
        <style>{'.grecaptcha-badge { visibility: hidden; }'}</style>
        <>{children}</>
      </body>
    </...>
  );
}
```

And then, on the page where we have the form and want to show the reCaptch logo, we can do this:

```
export default function FormPage(...) {
  return (
    <Form ...>
      <style>{'.grecaptcha-badge { visibility: visible; }'}</style>
      <>....</>
    </Form>
  );
}
```
