### ISSUE TITLE
Incorrect Token Format Issue with next-recaptcha-v3

### ISSUE THREAD

**Issue by jaosn60810** [snelsi/next-recaptcha-v3#158]
**Describe the bug**  
Using `next-recaptcha-v3` in a Next.js project leads to the generation of captcha tokens in an incorrect format, causing verification to fail.

**To Reproduce**  

1. Integrate `next-recaptcha-v3` with default setup.
2. Trigger captcha to generate a token for verification.
3. Observe the token format generated is incorrect.

**Expected behavior**  
Tokens generated should be in the correct format and allow for successful verification with reCAPTCHA v3.

**Screenshots**  
N/A

**Desktop (please complete the following information):**

- OS: [Your OS, e.g., Windows 10]
- Browser [Your browser, e.g., Chrome]
- Version [Your browser version, e.g., 89]

**Smartphone (please complete the following information):**  
N/A

**Additional context**  
Regenerating the reCAPTCHA keys from the Google Cloud Console temporarily resolves the issue, indicating it might be related to token handling or generation within `next-recaptcha-v3`.

**Comment by snelsi** [comment]
It appears that the issue you're experiencing might not directly stem from the `next-recaptcha-v3` library itself. The library simply triggers the reCAPTCHA token generation using the `grecaptcha.execute(key, { action })` function. This suggests that the problem might be elsewhere, potentially in how the token is handled or verified within your Next.js project.

**Comment by jaosn60810** [comment]
I realized the issue stemmed from my incorrect usage of the environment function. This misconfiguration prevented the dynamic retrieval of environment settings in GKE.

```tsx
// before
 < ReCaptchaProvider
   useEnterprise
   reCaptchaKey={process.env.NEXT_PUBLIC_GOOGLE_RECAPTCHA_V3_KEY}
   />

// after
 < ReCaptchaProvider
   useEnterprise
   reCaptchaKey={env('NEXT_PUBLIC_GOOGLE_RECAPTCHA_V3_KEY')}
   />
```
