### ISSUE TITLE
Why didn't version 1.4.0 publish to NPM

### ISSUE THREAD

**Issue by cycyewt** [snelsi/next-recaptcha-v3#159]
**Describe the bug**
1.3.0 still on NPM, https://www.npmjs.com/package/next-recaptcha-v3

**Comment by snelsi** [comment]
My bad, I'm very sorry

**Comment by snelsi** [comment]
[v1.4.1](https://www.npmjs.com/package/next-recaptcha-v3/v/1.4.1) should be live now.
Sorry for any inconvenience 🙏
