### ISSUE TITLE
Add Support for Nextjs 15 and React 19

### ISSUE THREAD

**Issue by LeandroGazoli** [snelsi/next-recaptcha-v3#161]
"peerDependencies": {
    "next": "^13.0.0 || ^14.0.0 || ^15.0.0",
    "react": ">=18.0.0",
    "react-dom": ">=18.0.0"
  },

**Comment by snelsi** [comment]
Added Next.js `v15` to `peerDependencies` in [v1.5.0](https://github.com/snelsi/next-recaptcha-v3/releases/tag/1.5.0).
Not sure if defining `>=18.0.0` covers canary React 19 releases though.

If you're using React 19, please give new version a try and tell if npm throws any warnings

**Comment by LeandroGazoli** [comment]
Perfect, thanks for the update. I will test here to see if everything works correctly with React 19 and let you know.

**Comment by LeandroGazoli** [comment]
Hi, regarding react 19, in its RC version it is running normally. TKS
