### ISSUE TITLE
Improve script loading time

### ISSUE THREAD

**Issue by gtokman** [snelsi/next-recaptcha-v3#162]
**Describe the bug**
Thanks for making this package! Not necessarily a bug, but I'm curious to get your thoughts. 

I ran a lighthouse test and saw the Google script takes some time to load which causes a hit on performance. Is there a way to make this script more effiecient? 
 
![CleanShot 2024-11-11 at 16 03 32@2x](https://github.com/user-attachments/assets/86f3f20f-178a-41e7-8341-19741e806aff)

**Comment by snelsi** [comment]
It's been a known issue for years at this point.
Google showed no interest in improving the situation whatsoever
https://github.com/google/recaptcha/issues/331

**Comment by gtokman** [comment]
@snelsi not surprised lol thanks!

**Comment by gtokman** [comment]
@snelsi What about adding a manual way to initiate the script? 

https://stackoverflow.com/questions/58982072/recaptcha-v3-assets-cause-pagespeed-issues-how-to-defer

I'm imagining an flag that is passed into the provider and then a function to initiate the script adhoc.

**Comment by gtokman** [comment]
Appreciate the examples! Thanks :)
