### ISSUE TITLE
Dependency Conflict Installing next-recaptcha-v3 with React 19 RC

### ISSUE THREAD

**Issue by Sathyaraj-dev** [snelsi/next-recaptcha-v3#163]
**Description**

When trying to install the next-recaptcha-v3 package in a Next.js 15 project using React 19 RC, an ERESOLVE error occurs due to a dependency conflict. The package does not seem to handle React 19 RC properly, even though it is supported by Next.js 15.

**The installation fails with the following error:**

npm error ERESOLVE unable to resolve dependency tree
npm error While resolving: test-next@0.1.0
npm error Found: react@19.0.0-rc-66855b96-20241106
npm error node_modules/react
npm error   react@"19.0.0-rc-66855b96-20241106" from the root project
npm error   peer react@"^18.2.0 || 19.0.0-rc-66855b96-20241106" from next@15.0.3
npm error   node_modules/next
npm error     next@"15.0.3" from the root project
npm error     peer next@"^13.0.0 || ^14.0.0 || ^15.0.0" from next-recaptcha-v3@1.5.0
npm error     node_modules/next-recaptcha-v3
npm error       next-recaptcha-v3@"*" from the root project
npm error   1 more (react-dom)
npm error
npm error Could not resolve dependency:
npm error peer react@">=18.0.0" from next-recaptcha-v3@1.5.0
npm error node_modules/next-recaptcha-v3
npm error   next-recaptcha-v3@"*" from the root project

**Expected Behavior**
The next-recaptcha-v3 package should install successfully, as its peerDependencies specify compatibility with React 18 or 19.

If there is a more permanent solution or workaround for this issue, please share it here. Thanks!

**Comment by snelsi** [comment]
Please try installing latest canary version:

```bash
npm i next-recaptcha-v3@1.5.1-canary.0
```

**Comment by Sathyaraj-dev** [comment]
Okay thanks
