### ISSUE TITLE
Allow to choose strategy

### ISSUE THREAD

**Issue by pegak** [snelsi/next-recaptcha-v3#42]
**Describe the solution you'd like**
Allow to pass loading strategy into the Provider.

**Describe alternatives you've considered**
Fork component and do it myself.

**Additional context**
Since Partytown will soon be in Next.js (currently experimental) it would be great to allow `worker` strategy (and possibly some other upcoming if they will ever come).

PS: Great job, I was looking for something directly for Next!

**Comment by snelsi** [comment]
All extra props from the Provider are passed directly to the Next.js Script tag:
https://github.com/snelsi/next-recaptcha-v3/blob/master/src/ReCaptchaProvider.tsx#:~:text=%7BonError%7D-,%7B...props%7D,-/%3E

You can configure `strategy` / `id` / `events` / `data-attributes` of the script tag however you like.

The only thing the Provider does, is creating a shared context of the script's loading state, so everything that uses ReCaptcha down the line can now, if it's ready to be used or not.

**Comment by pegak** [comment]
Thanks, missed this part in docs, but I see it is there.

**Comment by snelsi** [comment]
I'm closing this ticket for now. Feel free to reopen if you have any questions.
