### ISSUE TITLE
`executeRecaptcha` not referentially stable — mention in docs?

### ISSUE THREAD

**Issue by finkrer** [snelsi/next-recaptcha-v3#83]
I've just had an issue with using `executeRecaptcha`, and after debugging it turned out that this function actually changes its value. The first one is essentially just a stub that throws an error, and then, when reCaptcha loads, the value is updated with the working function.

Normally this isn't a problem, but I think that many people would expect that a function returned from a hook is referentially stable, as is usually the case with other hooks. So, when used in, say, a memoized event handler, it needs to be included as a dependency, otherwise the stub version is cached. I know you're supposed to include all functions, but it would be nice to have a reminder.

Besides, you could theoretically use the stub just by calling it fast enough. The hook even returns a `loaded` prop that could be used to check for it, but it's not mentioned anywhere.

I think this behavior needs to be explained in the docs, together with an explanation of how to use the function correctly.

Other than that, the library works great. Thanks!

**Comment by snelsi** [comment]
Good point, thank you 👍.

I will try to roll out a fix for this bug in a day or two.

**Comment by snelsi** [comment]
You can test this change in the latest canary branch by calling:
`npm i next-recaptcha-v3@1.1.0-canary.3`

**Comment by finkrer** [comment]
Finally gotten around to testing this — I don't know about `executeRecaptcha` specifically, but I now use the `loaded` prop to see when it's fine to use the captcha.

I actually previously caught some errors in Sentry due to the race condition I described earlier, but since I deployed the fix alongside your new version it all seems to be working fine.

**Comment by snelsi** [comment]
Sounds great then! 👌 
I'll merge and close this ticket when I have free time.

I was actually planning to release v1.1.0 this week, so keep an eye on that as well.

**Comment by snelsi** [comment]
Merged as part of the v1.1.0 release
